### ISSUE TITLE
Can not find currency from string

### ISSUE THREAD

**Issue by duongkstn** [scrapinghub/price-parser#38] opened 2020-06-09 02:53 UTC
When I type:
`Price.fromstring("Today I buy 3 coats with 300.000 VND")`
Your library returned:
`Price(amount=Decimal('3'), currency='VND')`
but the result I want is: `Price(amount=Decimal('300.000'), currency='VND')`

**Comment by Gallaecio** [comment] 2020-06-14 20:41
This is a duplicate of #2

**Closed** 2024-02-12 12:35 UTC
