### ISSUE TITLE
Get 3 letter currency name

### ISSUE THREAD

**Issue by botzill** [scrapinghub/price-parser#49] opened 2021-04-04 06:15 UTC
I have an example:

```
price = Price.fromstring("122$")
```

Is possible to get the `USD` as currency instead of `$`?

**Comment by Gallaecio** [comment] 2021-04-05 13:05
This is a duplicate of https://github.com/scrapinghub/price-parser/issues/28

**Closed by Gallaecio** 2021-04-05 13:05 UTC
